In [3]:
# Cell 1 — install (only needed once per Colab session)
!pip install -q datasets

# Cell 2 — load and preview one row from natural-plan-calendar
import pandas as pd
from datasets import load_dataset

# Don't let pandas truncate long values when we DO want to see them,
# and don't let it wrap the row index column awkwardly.
pd.set_option("display.max_colwidth", 100)   # truncate long cells to 100 chars
pd.set_option("display.width", 120)

ds = load_dataset("anakin87/events-scheduling", split="test")
df = pd.DataFrame(ds)

print(f"Total records: {len(df)}")
print(f"Columns ({len(df.columns)}): {list(df.columns)}\n")

# Show one record as a vertical column–value table, matching Figure 3.1 style
sample = df.iloc[[0]].T
sample.columns = ["Row 1"]
sample

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/71.4k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/21.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/100 [00:00<?, ? examples/s]

Total records: 100
Columns (4): ['events', 'priority_events', 'optimal_score', 'prompt']

                                                                                                               Row 1
events           [[The Killers concert, 00:22, 00:37], [Sum 41 concert, 02:19, 03:04], [Jam session, 07:47, 09:17...
priority_events                                                                 [Backstage tour VIP pass, Fireworks]
optimal_score                                                                                                    315
prompt           Events:\n- The Killers concert (00:22 - 00:37)\n- Sum 41 concert (02:19 - 03:04)\n- Jam session ...

In [2]:
# Cell 1 — install (only needed once per Colab session)
!pip install -q datasets

# Cell 2 — load and preview one row from natural-plan-calendar
import pandas as pd
from datasets import load_dataset

# Don't let pandas truncate long values when we DO want to see them,
# and don't let it wrap the row index column awkwardly.
pd.set_option("display.max_colwidth", 100)   # truncate long cells to 100 chars
pd.set_option("display.width", 120)

ds = load_dataset("clembench-playpen/natural-plan-calendar", split="default")
df = pd.DataFrame(ds)

print(f"Total records: {len(df)}")
print(f"Columns ({len(df.columns)}): {list(df.columns)}\n")

# Show one record as a vertical column–value table, matching Figure 3.1 style
sample = df.iloc[[0]].T
sample.columns = ["Row 1"]
sample

Total records: 1000
Columns (8): ['id', 'num_people', 'num_days', 'duration', 'prompt_0shot', 'prompt_5shot', 'golden_plan', 'pred_5shot_gemini_pro']

                                                                                                                     Row 1
id                                                                                           calendar_scheduling_example_0
num_people                                                                                                               3
num_days                                                                                                                 1
duration                                                                                                                 1
prompt_0shot           You are an expert at scheduling meetings. You are given a few constraints on the existing schedu...
prompt_5shot           You are an expert at scheduling meetings. You are given a few constraints on the existing schedu...
golden_plan                                                              Here is the proposed time: Monday, 14:30 - 15:30
pred_5shot_gemini_pro                                        SOLUTION: Here is the proposed time: Monday, 14:30 - 15:30 \n

In [4]:
# Cell 1 — install (only needed once per Colab session)
!pip install -q datasets

# Cell 2 — load and preview one row from natural-plan-calendar
import pandas as pd
from datasets import load_dataset

# Don't let pandas truncate long values when we DO want to see them,
# and don't let it wrap the row index column awkwardly.
pd.set_option("display.max_colwidth", 100)   # truncate long cells to 100 chars
pd.set_option("display.width", 120)

ds = load_dataset("vidhikatkoria/DA_SGD_Calendar", split="train")
df = pd.DataFrame(ds)

print(f"Total records: {len(df)}")
print(f"Columns ({len(df.columns)}): {list(df.columns)}\n")

# Show one record as a vertical column–value table, matching Figure 3.1 style
sample = df.iloc[[0]].T
sample.columns = ["Row 1"]
sample

README.md:   0%|          | 0.00/570 [00:00<?, ?B/s]

data/train-00000-of-00001-be35259273ac2b(…):   0%|          | 0.00/86.9k [00:00<?, ?B/s]

data/test-00000-of-00001-33b5618086fbd15(…):   0%|          | 0.00/3.19k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1029 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1 [00:00<?, ? examples/s]

Total records: 1029
Columns (5): ['domain', 'context', 'response', 'act', 'speaker']

                                                                                                        Row 1
domain                                                                                               Calendar
context   Agent: Would you like to add any events. <SEP> User: Yes, please. Add the event in location Home...
response                                                                      Put Bedtime as the event title.
act                                                                                                         3
speaker                                                                                                     0